### ISSUE TITLE
Task Center - My Tasks Requests Tab: what is the need for showing the complete action if it will not be clickable? 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#45] opened 2022-10-03 11:18 UTC
what is the need for showing this if it will not be clickable in my requests tab? 

![image](https://user-images.githubusercontent.com/110157969/193564126-2beca9df-33e6-4588-9ca9-b0fbc3c14aaf.png)

**Comment by KhaldounAl-haj** [comment] 2022-10-04 19:02
it is clickable when you change the progress. @DemaHamideh

**Comment by KhaldounAl-haj** [comment] 2022-10-04 19:07
@JarrarMo please check this issue it is a bug

**Comment by DemaHamideh** [comment] 2022-10-05 06:36
@KhaldounAl-haj this is my requests tab, thus, the requester can change the progress for tasks assigned to other users? I believe this is not applicable. 
anyway, this is also an issue in the vanilla version.

**Comment by KhaldounAl-haj** [comment] 2022-10-05 07:07
@DemaHamideh we are discussing this if the user is looking at his tasks the user is unable to edit progress for his tasks also here

**Comment by KhaldounAl-haj** [comment] 2022-10-24 12:16
@DemaHamideh if the task is completed the circle shall be filled and its not clickable because this is the user's requests the assigned user shall be able to edit this on "My tasks" tab "my requests" tab shall be not editable for the user.

@JarrarMo please either you make sure the circle is filled when the task is completed or remove the circle

**Comment by KhaldounAl-haj** [comment] 2022-10-24 12:29
@DemaHamideh this is not a bug neither an enhancement close it please it works well

**Closed** 2022-10-25 06:39 UTC
Labels: P3 (Normal), Iteration 1, Business issue
